name: Build and deploy Angular app to Azure Web App - bakejoli-dev

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --if-present

      - name: Compress build artifacts
        run: zip -r build-artifacts.zip dist/bake-joli-web-app  # Compress the correct directory

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: build-artifacts.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Extract build artifacts
        run: unzip build-artifacts.zip -d build-output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0F6C4D2244894A0A8821CC514E645AB6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A9266CD4E75E4BFA973EC173F6A55413 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_57521A0AC30E499BA144215C2AB9AFCD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'bakejoli-dev'
          slot-name: 'Production'
          package: build-output/dist/bake-joli-web-app/browser  # Adjust path to where the extracted files are located
